#include <stdexcept>
#include <string>
#include <unordered_map>

#include <util/Abort.h>
#include <vkr/image/ImageFormatFeatures.h>

using namespace mt;

using FormatsMap = std::unordered_map<VkFormat, ImageFormatFeatures>;
FormatsMap formatsMap =
  {
    {VK_FORMAT_R8_UINT,         { .name = "VK_FORMAT_R8_UINT",
                                  .format = VK_FORMAT_R8_UINT,
                                  .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                                  .isColor = true,
                                  .hasR = true,
                                  .hasG = false,
                                  .hasB = false,
                                  .hasA = false,
                                  .isDepthStencil = false,
                                  .hasDepth = false,
                                  .hasStencil = false,
                                  .texelSize = 8,
                                  .isCompressed = false}},

    {VK_FORMAT_R8G8B8_UNORM,    { .name = "VK_FORMAT_R8G8B8_UNORM",
                                  .format = VK_FORMAT_R8G8B8_UNORM,
                                  .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                                  .isColor = true,
                                  .hasR = true,
                                  .hasG = true,
                                  .hasB = true,
                                  .hasA = false,
                                  .isDepthStencil = false,
                                  .hasDepth = false,
                                  .hasStencil = false,
                                  .texelSize = 24,
                                  .isCompressed = false}},
    {VK_FORMAT_R8G8B8_SRGB,     { .name = "VK_FORMAT_R8G8B8_SRGB",
                                  .format = VK_FORMAT_R8G8B8_SRGB,
                                  .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                                  .isColor = true,
                                  .hasR = true,
                                  .hasG = true,
                                  .hasB = true,
                                  .hasA = false,
                                  .isDepthStencil = false,
                                  .hasDepth = false,
                                  .hasStencil = false,
                                  .texelSize = 24,
                                  .isCompressed = false}},
    {VK_FORMAT_R8G8B8A8_UNORM,  { .name = "VK_FORMAT_R8G8B8A8_UNORM",
                                  .format = VK_FORMAT_R8G8B8A8_UNORM,
                                  .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                                  .isColor = true,
                                  .hasR = true,
                                  .hasG = true,
                                  .hasB = true,
                                  .hasA = true,
                                  .isDepthStencil = false,
                                  .hasDepth = false,
                                  .hasStencil = false,
                                  .texelSize = 32,
                                  .isCompressed = false}},
    {VK_FORMAT_B8G8R8A8_SRGB,   { .name = "VK_FORMAT_B8G8R8A8_SRGB",
                                  .format = VK_FORMAT_B8G8R8A8_SRGB,
                                  .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                                  .isColor = true,
                                  .hasR = true,
                                  .hasG = true,
                                  .hasB = true,
                                  .hasA = true,
                                  .isDepthStencil = false,
                                  .hasDepth = false,
                                  .hasStencil = false,
                                  .texelSize = 32,
                                  .isCompressed = false}},

    {VK_FORMAT_R32G32B32A32_SFLOAT,
                                { .name = "VK_FORMAT_R32G32B32A32_SFLOAT",
                                  .format = VK_FORMAT_R32G32B32A32_SFLOAT,
                                  .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                                  .isColor = true,
                                  .hasR = true,
                                  .hasG = true,
                                  .hasB = true,
                                  .hasA = true,
                                  .isDepthStencil = false,
                                  .hasDepth = false,
                                  .hasStencil = false,
                                  .texelSize = 128,
                                  .isCompressed = false}},

    {VK_FORMAT_BC1_RGB_UNORM_BLOCK,
                                { .name = "VK_FORMAT_BC1_RGB_UNORM_BLOCK",
                                  .format = VK_FORMAT_BC1_RGB_UNORM_BLOCK,
                                  .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                                  .isColor = true,
                                  .hasR = true,
                                  .hasG = true,
                                  .hasB = true,
                                  .hasA = false,
                                  .isDepthStencil = false,
                                  .hasDepth = false,
                                  .hasStencil = false,
                                  .texelSize = 4,
                                  .isCompressed = true}},
    {VK_FORMAT_BC1_RGB_SRGB_BLOCK,
                                {.name = "VK_FORMAT_BC1_RGB_SRGB_BLOCK",
                                  .format = VK_FORMAT_BC1_RGB_SRGB_BLOCK,
                                  .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                                  .isColor = true,
                                  .hasR = true,
                                  .hasG = true,
                                  .hasB = true,
                                  .hasA = false,
                                  .isDepthStencil = false,
                                  .hasDepth = false,
                                  .hasStencil = false,
                                  .texelSize = 4,
                                  .isCompressed = true}},
    {VK_FORMAT_BC1_RGBA_UNORM_BLOCK,
                                { .name = "VK_FORMAT_BC1_RGBA_UNORM_BLOCK",
                                  .format = VK_FORMAT_BC1_RGBA_UNORM_BLOCK,
                                  .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                                  .isColor = true,
                                  .hasR = true,
                                  .hasG = true,
                                  .hasB = true,
                                  .hasA = true,
                                  .isDepthStencil = false,
                                  .hasDepth = false,
                                  .hasStencil = false,
                                  .texelSize = 4,
                                  .isCompressed = true}},
    {VK_FORMAT_BC1_RGBA_SRGB_BLOCK,
                                { .name = "VK_FORMAT_BC1_RGBA_SRGB_BLOCK",
                                  .format = VK_FORMAT_BC1_RGBA_SRGB_BLOCK,
                                  .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                                  .isColor = true,
                                  .hasR = true,
                                  .hasG = true,
                                  .hasB = true,
                                  .hasA = true,
                                  .isDepthStencil = false,
                                  .hasDepth = false,
                                  .hasStencil = false,
                                  .texelSize = 4,
                                  .isCompressed = true}},
    { VK_FORMAT_BC2_UNORM_BLOCK,
                                { .name = "VK_FORMAT_BC2_UNORM_BLOCK",
                                  .format = VK_FORMAT_BC2_UNORM_BLOCK,
                                  .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                                  .isColor = true,
                                  .hasR = true,
                                  .hasG = true,
                                  .hasB = true,
                                  .hasA = true,
                                  .isDepthStencil = false,
                                  .hasDepth = false,
                                  .hasStencil = false,
                                  .texelSize = 8,
                                  .isCompressed = true}},
    { VK_FORMAT_BC2_SRGB_BLOCK,
                                { .name = "VK_FORMAT_BC2_SRGB_BLOCK",
                                  .format = VK_FORMAT_BC2_SRGB_BLOCK,
                                  .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                                  .isColor = true,
                                  .hasR = true,
                                  .hasG = true,
                                  .hasB = true,
                                  .hasA = true,
                                  .isDepthStencil = false,
                                  .hasDepth = false,
                                  .hasStencil = false,
                                  .texelSize = 8,
                                  .isCompressed = true}},
    { VK_FORMAT_BC3_UNORM_BLOCK,
                                { .name = "VK_FORMAT_BC3_UNORM_BLOCK",
                                  .format = VK_FORMAT_BC3_UNORM_BLOCK,
                                  .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                                  .isColor = true,
                                  .hasR = true,
                                  .hasG = true,
                                  .hasB = true,
                                  .hasA = true,
                                  .isDepthStencil = false,
                                  .hasDepth = false,
                                  .hasStencil = false,
                                  .texelSize = 8,
                                  .isCompressed = true}},
    { VK_FORMAT_BC3_SRGB_BLOCK,
                                { .name = "VK_FORMAT_BC3_SRGB_BLOCK",
                                  .format = VK_FORMAT_BC3_SRGB_BLOCK,
                                  .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                                  .isColor = true,
                                  .hasR = true,
                                  .hasG = true,
                                  .hasB = true,
                                  .hasA = true,
                                  .isDepthStencil = false,
                                  .hasDepth = false,
                                  .hasStencil = false,
                                  .texelSize = 8,
                                  .isCompressed = true}},
    { VK_FORMAT_BC4_UNORM_BLOCK,
                                { .name = "VK_FORMAT_BC4_UNORM_BLOCK",
                                  .format = VK_FORMAT_BC4_UNORM_BLOCK,
                                  .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                                  .isColor = true,
                                  .hasR = true,
                                  .hasG = false,
                                  .hasB = false,
                                  .hasA = false,
                                  .isDepthStencil = false,
                                  .hasDepth = false,
                                  .hasStencil = false,
                                  .texelSize = 4,
                                  .isCompressed = true}},
    { VK_FORMAT_BC4_SNORM_BLOCK,
                                { .name = "VK_FORMAT_BC4_SNORM_BLOCK",
                                  .format = VK_FORMAT_BC4_SNORM_BLOCK,
                                  .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                                  .isColor = true,
                                  .hasR = true,
                                  .hasG = false,
                                  .hasB = false,
                                  .hasA = false,
                                  .isDepthStencil = false,
                                  .hasDepth = false,
                                  .hasStencil = false,
                                  .texelSize = 4,
                                  .isCompressed = true}},
    { VK_FORMAT_BC5_UNORM_BLOCK,
                                { .name = "VK_FORMAT_BC5_UNORM_BLOCK",
                                  .format = VK_FORMAT_BC5_UNORM_BLOCK,
                                  .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                                  .isColor = true,
                                  .hasR = true,
                                  .hasG = true,
                                  .hasB = false,
                                  .hasA = false,
                                  .isDepthStencil = false,
                                  .hasDepth = false,
                                  .hasStencil = false,
                                  .texelSize = 8,
                                  .isCompressed = true}},
    { VK_FORMAT_BC5_SNORM_BLOCK,
                                { .name = "VK_FORMAT_BC5_SNORM_BLOCK",
                                  .format = VK_FORMAT_BC5_SNORM_BLOCK,
                                  .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                                  .isColor = true,
                                  .hasR = true,
                                  .hasG = true,
                                  .hasB = false,
                                  .hasA = false,
                                  .isDepthStencil = false,
                                  .hasDepth = false,
                                  .hasStencil = false,
                                  .texelSize = 8,
                                  .isCompressed = true}},
    { VK_FORMAT_BC6H_UFLOAT_BLOCK,
                                { .name = "VK_FORMAT_BC6H_UFLOAT_BLOCK",
                                  .format = VK_FORMAT_BC6H_UFLOAT_BLOCK,
                                  .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                                  .isColor = true,
                                  .hasR = true,
                                  .hasG = true,
                                  .hasB = true,
                                  .hasA = false,
                                  .isDepthStencil = false,
                                  .hasDepth = false,
                                  .hasStencil = false,
                                  .texelSize = 8,
                                  .isCompressed = true}},
    { VK_FORMAT_BC6H_SFLOAT_BLOCK,
                                { .name = "VK_FORMAT_BC6H_SFLOAT_BLOCK",
                                  .format = VK_FORMAT_BC6H_SFLOAT_BLOCK,
                                  .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                                  .isColor = true,
                                  .hasR = true,
                                  .hasG = true,
                                  .hasB = true,
                                  .hasA = false,
                                  .isDepthStencil = false,
                                  .hasDepth = false,
                                  .hasStencil = false,
                                  .texelSize = 8,
                                  .isCompressed = true}},
    { VK_FORMAT_BC7_UNORM_BLOCK,
                                { .name = "VK_FORMAT_BC7_UNORM_BLOCK",
                                  .format = VK_FORMAT_BC7_UNORM_BLOCK,
                                  .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                                  .isColor = true,
                                  .hasR = true,
                                  .hasG = true,
                                  .hasB = true,
                                  .hasA = true,
                                  .isDepthStencil = false,
                                  .hasDepth = false,
                                  .hasStencil = false,
                                  .texelSize = 8,
                                  .isCompressed = true}},
    { VK_FORMAT_BC7_SRGB_BLOCK,
                                { .name = "VK_FORMAT_BC7_SRGB_BLOCK",
                                  .format = VK_FORMAT_BC7_SRGB_BLOCK,
                                  .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
                                  .isColor = true,
                                  .hasR = true,
                                  .hasG = true,
                                  .hasB = true,
                                  .hasA = true,
                                  .isDepthStencil = false,
                                  .hasDepth = false,
                                  .hasStencil = false,
                                  .texelSize = 8,
                                  .isCompressed = true}},

    {VK_FORMAT_D16_UNORM,       { .name = "VK_FORMAT_D16_UNORM",
                                  .format = VK_FORMAT_D16_UNORM,
                                  .aspectMask = VK_IMAGE_ASPECT_DEPTH_BIT,
                                  .isColor = false,
                                  .hasR = false,
                                  .hasG = false,
                                  .hasB = false,
                                  .hasA = false,
                                  .isDepthStencil = true,
                                  .hasDepth = true,
                                  .hasStencil = false,
                                  .texelSize = 16,
                                  .isCompressed = false}},
    {VK_FORMAT_X8_D24_UNORM_PACK32,
                                { .name = "VK_FORMAT_X8_D24_UNORM_PACK32",
                                  .format = VK_FORMAT_X8_D24_UNORM_PACK32,
                                  .aspectMask = VK_IMAGE_ASPECT_DEPTH_BIT,
                                  .isColor = false,
                                  .hasR = false,
                                  .hasG = false,
                                  .hasB = false,
                                  .hasA = false,
                                  .isDepthStencil = true,
                                  .hasDepth = true,
                                  .hasStencil = false,
                                  .texelSize = 32,
                                  .isCompressed = false}},
    {VK_FORMAT_D32_SFLOAT,      { .name = "VK_FORMAT_D32_SFLOAT",
                                  .format = VK_FORMAT_D32_SFLOAT,
                                  .aspectMask = VK_IMAGE_ASPECT_DEPTH_BIT,
                                  .isColor = false,
                                  .hasR = false,
                                  .hasG = false,
                                  .hasB = false,
                                  .hasA = false,
                                  .isDepthStencil = true,
                                  .hasDepth = true,
                                  .hasStencil = false,
                                  .texelSize = 32,
                                  .isCompressed = false}},
    {VK_FORMAT_S8_UINT,         { .name = "VK_FORMAT_S8_UINT",
                                  .format = VK_FORMAT_S8_UINT,
                                  .aspectMask = VK_IMAGE_ASPECT_STENCIL_BIT,
                                  .isColor = false,
                                  .hasR = false,
                                  .hasG = false,
                                  .hasB = false,
                                  .hasA = false,
                                  .isDepthStencil = true,
                                  .hasDepth = false,
                                  .hasStencil = true,
                                  .texelSize = 8,
                                  .isCompressed = false}},
    {VK_FORMAT_D16_UNORM_S8_UINT,
                                { .name = "VK_FORMAT_D16_UNORM_S8_UINT",
                                  .format = VK_FORMAT_D16_UNORM_S8_UINT,
                                  .aspectMask = VK_IMAGE_ASPECT_DEPTH_BIT |
                                                VK_IMAGE_ASPECT_STENCIL_BIT,
                                  .isColor = false,
                                  .hasR = false,
                                  .hasG = false,
                                  .hasB = false,
                                  .hasA = false,
                                  .isDepthStencil = true,
                                  .hasDepth = true,
                                  .hasStencil = true,
                                  .texelSize = 24,
                                  .isCompressed = false}},
    {VK_FORMAT_D24_UNORM_S8_UINT,
                                { .name = "VK_FORMAT_D24_UNORM_S8_UINT",
                                  .format = VK_FORMAT_D24_UNORM_S8_UINT,
                                  .aspectMask = VK_IMAGE_ASPECT_DEPTH_BIT |
                                                VK_IMAGE_ASPECT_STENCIL_BIT,
                                  .isColor = false,
                                  .hasR = false,
                                  .hasG = false,
                                  .hasB = false,
                                  .hasA = false,
                                  .isDepthStencil = true,
                                  .hasDepth = true,
                                  .hasStencil = true,
                                  .texelSize = 32,
                                  .isCompressed = false}},
    {VK_FORMAT_D32_SFLOAT_S8_UINT,
                                { .name = "VK_FORMAT_D32_SFLOAT_S8_UINT",
                                  .format = VK_FORMAT_D32_SFLOAT_S8_UINT,
                                  .aspectMask = VK_IMAGE_ASPECT_DEPTH_BIT |
                                                VK_IMAGE_ASPECT_STENCIL_BIT,
                                  .isColor = false,
                                  .hasR = false,
                                  .hasG = false,
                                  .hasB = false,
                                  .hasA = false,
                                  .isDepthStencil = true,
                                  .hasDepth = true,
                                  .hasStencil = true,
                                  .texelSize = 64,
                                  .isCompressed = false}}
  };

const ImageFormatFeatures& mt::getFormatFeatures(VkFormat format)
{
  FormatsMap::const_iterator iFeature = formatsMap.find(format);
  if(iFeature == formatsMap.end()) throw std::runtime_error("ImageFormatFeatures: unable to find format " + std::to_string(format));
  return iFeature->second;
}

const ImageFormatFeatures& mt::getFormatFeatures(const std::string& formatName)
{
  for(FormatsMap::const_iterator iFeature = formatsMap.begin();
      iFeature != formatsMap.end();
      iFeature++)
  {
    if(iFeature->second.name == formatName) return iFeature->second;
  }

  throw std::runtime_error("ImageFormatFeatures: unable to find format " + formatName);
}
