#include <vulkan/vulkan.h>

#include <util/Bimap.h>
#include <vkr/pipeline/AbstractPipeline.h>

namespace mt
{
  const Bimap<AbstractPipeline::Type> pipelineMap
  {
    "PipelineTypeMap",
    {
      {AbstractPipeline::GRAPHIC_PIPELINE, "GRAPHIC_PIPELINE"},
      {AbstractPipeline::COMPUTE_PIPELINE, "COMPUTE_PIPELINE"}
    }
  };

  const Bimap<VkShaderStageFlagBits> shaderStageMap
  {
    "ShaderStageMap",
    {
      {VK_SHADER_STAGE_VERTEX_BIT, "VERTEX"},
      {VK_SHADER_STAGE_TESSELLATION_CONTROL_BIT, "TESSELLATION_CONTROL"},
      {VK_SHADER_STAGE_TESSELLATION_EVALUATION_BIT, "TESSELLATION_EVALUATION"},
      {VK_SHADER_STAGE_GEOMETRY_BIT, "GEOMETRY"},
      {VK_SHADER_STAGE_FRAGMENT_BIT, "FRAGMENT"},
      {VK_SHADER_STAGE_COMPUTE_BIT, "COMPUTE"},
      {VK_SHADER_STAGE_RAYGEN_BIT_KHR, "RAYGEN"},
      {VK_SHADER_STAGE_ANY_HIT_BIT_KHR, "ANY_HIT"},
      {VK_SHADER_STAGE_CLOSEST_HIT_BIT_KHR, "CLOSEST_HIT"},
      {VK_SHADER_STAGE_MISS_BIT_KHR, "MISS"},
      {VK_SHADER_STAGE_INTERSECTION_BIT_KHR, "INTERSECTION"},
      {VK_SHADER_STAGE_CALLABLE_BIT_KHR, "CALLABLE"},
      {VK_SHADER_STAGE_TASK_BIT_EXT, "TASK"},
      {VK_SHADER_STAGE_MESH_BIT_EXT, "MESH"}
    }
  };

  const Bimap<VkSampleCountFlagBits> sampleCountMap
  {
    "SampleCountMap",
    {
      {VK_SAMPLE_COUNT_1_BIT, "SAMPLE_COUNT_1"},
      {VK_SAMPLE_COUNT_2_BIT, "SAMPLE_COUNT_2"},
      {VK_SAMPLE_COUNT_4_BIT, "SAMPLE_COUNT_4"},
      {VK_SAMPLE_COUNT_8_BIT, "SAMPLE_COUNT_8"},
      {VK_SAMPLE_COUNT_16_BIT, "SAMPLE_COUNT_16"},
      {VK_SAMPLE_COUNT_32_BIT, "SAMPLE_COUNT_32"},
      {VK_SAMPLE_COUNT_64_BIT, "SAMPLE_COUNT_64"}
    }
  };

  const Bimap<VkPrimitiveTopology> topologyMap
  {
    "TopologyMap",
    {
      {VK_PRIMITIVE_TOPOLOGY_POINT_LIST, "POINT_LIST"},
      {VK_PRIMITIVE_TOPOLOGY_LINE_LIST, "LINE_LIST"},
      {VK_PRIMITIVE_TOPOLOGY_LINE_STRIP, "LINE_STRIP"},
      {VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST, "TRIANGLE_LIST"},
      {VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP, "TRIANGLE_STRIP"},
      {VK_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN, "TRIANGLE_FAN"},
      {VK_PRIMITIVE_TOPOLOGY_LINE_LIST_WITH_ADJACENCY, "LINE_LIST_WITH_ADJACENCY"},
      {VK_PRIMITIVE_TOPOLOGY_LINE_STRIP_WITH_ADJACENCY, "LINE_STRIP_WITH_ADJACENCY"},
      {VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST_WITH_ADJACENCY, "TRIANGLE_LIST_WITH_ADJACENCY"},
      {VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP_WITH_ADJACENCY, "TRIANGLE_STRIP_WITH_ADJACENCY"},
      {VK_PRIMITIVE_TOPOLOGY_PATCH_LIST, "PATCH_LIST"}
    }
  };

  const Bimap<VkPolygonMode> polygonModeMap
  {
    "PolygonModeMap",
    {
      {VK_POLYGON_MODE_FILL, "FILL"},
      {VK_POLYGON_MODE_LINE, "LINE"},
      {VK_POLYGON_MODE_POINT, "POINT"}
    }
  };

  const Bimap<VkCullModeFlagBits> cullModeMap
  {
    "CullModeMap",
    {
      {VK_CULL_MODE_NONE, "NONE"},
      {VK_CULL_MODE_FRONT_BIT, "FRONT"},
      {VK_CULL_MODE_BACK_BIT, "BACK"},
      {VK_CULL_MODE_FRONT_AND_BACK, "FRONT_AND_BACK"}
    }
  };

  const Bimap<VkFrontFace> fronFaceMap
  {
    "FronFaceMap",
    {
      {VK_FRONT_FACE_COUNTER_CLOCKWISE, "COUNTER_CLOCKWISE"},
      {VK_FRONT_FACE_CLOCKWISE, "CLOCKWISE"}
    }
  };

  const Bimap<VkCompareOp> compareOpMap
  {
    "CompareOpMap",
    {
      {VK_COMPARE_OP_NEVER, "NEVER"},
      {VK_COMPARE_OP_LESS, "LESS"},
      {VK_COMPARE_OP_EQUAL, "EQUAL"},
      {VK_COMPARE_OP_LESS_OR_EQUAL, "LESS_OR_EQUAL"},
      {VK_COMPARE_OP_GREATER, "GREATER"},
      {VK_COMPARE_OP_NOT_EQUAL, "NOT_EQUAL"},
      {VK_COMPARE_OP_GREATER_OR_EQUAL, "GREATER_OR_EQUAL"},
      {VK_COMPARE_OP_ALWAYS, "ALWAYS"}
    }
  };

  const Bimap<VkStencilOp> stencilOpMap
  {
    "StencilOpMap",
    {
      {VK_STENCIL_OP_KEEP, "KEEP"},
      {VK_STENCIL_OP_ZERO, "ZERO"},
      {VK_STENCIL_OP_REPLACE, "REPLACE"},
      {VK_STENCIL_OP_INCREMENT_AND_CLAMP, "INCREMENT_AND_CLAMP"},
      {VK_STENCIL_OP_DECREMENT_AND_CLAMP, "DECREMENT_AND_CLAMP"},
      {VK_STENCIL_OP_INVERT, "INVERT"},
      {VK_STENCIL_OP_INCREMENT_AND_WRAP, "INCREMENT_AND_WRAP"},
      {VK_STENCIL_OP_DECREMENT_AND_WRAP, "DECREMENT_AND_WRAP"}
    }
  };

  const Bimap<VkBlendFactor> blendFactorMap
  {
    "BlendFactorMap",
    {
      {VK_BLEND_FACTOR_ZERO, "ZERO"},
      {VK_BLEND_FACTOR_ONE, "ONE"},
      {VK_BLEND_FACTOR_SRC_COLOR, "SRC_COLOR"},
      {VK_BLEND_FACTOR_ONE_MINUS_SRC_COLOR, "ONE_MINUS_SRC_COLOR"},
      {VK_BLEND_FACTOR_DST_COLOR, "DST_COLOR"},
      {VK_BLEND_FACTOR_ONE_MINUS_DST_COLOR, "ONE_MINUS_DST_COLOR"},
      {VK_BLEND_FACTOR_SRC_ALPHA, "SRC_ALPHA"},
      {VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA, "ONE_MINUS_SRC_ALPHA"},
      {VK_BLEND_FACTOR_DST_ALPHA, "DST_ALPHA"},
      {VK_BLEND_FACTOR_ONE_MINUS_DST_ALPHA, "ONE_MINUS_DST_ALPHA"},
      {VK_BLEND_FACTOR_CONSTANT_COLOR, "CONSTANT_COLOR"},
      {VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_COLOR, "ONE_MINUS_CONSTANT_COLOR"},
      {VK_BLEND_FACTOR_CONSTANT_ALPHA, "CONSTANT_ALPHA"},
      {VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_ALPHA, "ONE_MINUS_CONSTANT_ALPHA"},
      {VK_BLEND_FACTOR_SRC_ALPHA_SATURATE, "SRC_ALPHA_SATURATE"},
      {VK_BLEND_FACTOR_SRC1_COLOR, "SRC1_COLOR"},
      {VK_BLEND_FACTOR_ONE_MINUS_SRC1_COLOR, "ONE_MINUS_SRC1_COLOR"},
      {VK_BLEND_FACTOR_SRC1_ALPHA, "SRC1_ALPHA"},
      {VK_BLEND_FACTOR_ONE_MINUS_SRC1_ALPHA, "ONE_MINUS_SRC1_ALPHA"}
    }
  };

  const Bimap<VkBlendOp> blendOpMap
  {
    "BlendOpMap",
    {
      {VK_BLEND_OP_ADD, "ADD"},
      {VK_BLEND_OP_SUBTRACT, "SUBTRACT"},
      {VK_BLEND_OP_REVERSE_SUBTRACT, "REVERSE_SUBTRACT"},
      {VK_BLEND_OP_MIN, "MIN"},
      {VK_BLEND_OP_MAX, "MAX"},
      {VK_BLEND_OP_ZERO_EXT, "ZERO"},
      {VK_BLEND_OP_SRC_EXT, "SRC"},
      {VK_BLEND_OP_DST_EXT, "DST"},
      {VK_BLEND_OP_SRC_OVER_EXT, "SRC_OVER"},
      {VK_BLEND_OP_DST_OVER_EXT, "DST_OVER"},
      {VK_BLEND_OP_SRC_IN_EXT, "SRC_IN"},
      {VK_BLEND_OP_DST_IN_EXT, "DST_IN"},
      {VK_BLEND_OP_SRC_OUT_EXT, "SRC_OUT"},
      {VK_BLEND_OP_DST_OUT_EXT, "DST_OUT"},
      {VK_BLEND_OP_SRC_ATOP_EXT, "SRC_ATOP"},
      {VK_BLEND_OP_DST_ATOP_EXT, "DST_ATOP"},
      {VK_BLEND_OP_XOR_EXT, "XOR"},
      {VK_BLEND_OP_MULTIPLY_EXT, "MULTIPLY"},
      {VK_BLEND_OP_SCREEN_EXT, "SCREEN"},
      {VK_BLEND_OP_OVERLAY_EXT, "OVERLAY"},
      {VK_BLEND_OP_DARKEN_EXT, "DARKEN"},
      {VK_BLEND_OP_LIGHTEN_EXT, "LIGHTEN"},
      {VK_BLEND_OP_COLORDODGE_EXT, "COLORDODGE"},
      {VK_BLEND_OP_COLORBURN_EXT, "COLORBURN"},
      {VK_BLEND_OP_HARDLIGHT_EXT, "HARDLIGHT"},
      {VK_BLEND_OP_SOFTLIGHT_EXT, "SOFTLIGHT"},
      {VK_BLEND_OP_DIFFERENCE_EXT, "DIFFERENCE"},
      {VK_BLEND_OP_EXCLUSION_EXT, "EXCLUSION"},
      {VK_BLEND_OP_INVERT_EXT, "INVERT"},
      {VK_BLEND_OP_INVERT_RGB_EXT, "INVERT_RGB"},
      {VK_BLEND_OP_LINEARDODGE_EXT, "LINEARDODGE"},
      {VK_BLEND_OP_LINEARBURN_EXT, "LINEARBURN"},
      {VK_BLEND_OP_VIVIDLIGHT_EXT, "VIVIDLIGHT"},
      {VK_BLEND_OP_LINEARLIGHT_EXT, "LINEARLIGHT"},
      {VK_BLEND_OP_PINLIGHT_EXT, "PINLIGHT"},
      {VK_BLEND_OP_HARDMIX_EXT, "HARDMIX"},
      {VK_BLEND_OP_HSL_HUE_EXT, "HSL_HUE"},
      {VK_BLEND_OP_HSL_SATURATION_EXT, "HSL_SATURATION"},
      {VK_BLEND_OP_HSL_COLOR_EXT, "HSL_COLOR"},
      {VK_BLEND_OP_HSL_LUMINOSITY_EXT, "HSL_LUMINOSITY"},
      {VK_BLEND_OP_PLUS_EXT, "PLUS"},
      {VK_BLEND_OP_PLUS_CLAMPED_EXT, "PLUS_CLAMPED"},
      {VK_BLEND_OP_PLUS_CLAMPED_ALPHA_EXT, "PLUS_CLAMPED_ALPHA"},
      {VK_BLEND_OP_PLUS_DARKER_EXT, "PLUS_DARKER"},
      {VK_BLEND_OP_MINUS_EXT, "MINUS"},
      {VK_BLEND_OP_MINUS_CLAMPED_EXT, "MINUS_CLAMPED"},
      {VK_BLEND_OP_CONTRAST_EXT, "CONTRAST"},
      {VK_BLEND_OP_INVERT_OVG_EXT, "INVERT_OVG"},
      {VK_BLEND_OP_RED_EXT, "RED"},
      {VK_BLEND_OP_GREEN_EXT, "GREEN"},
      {VK_BLEND_OP_BLUE_EXT, "BLUE"}
    }
  };

  const Bimap<VkColorComponentFlagBits> colorComponentMap
  {
    "ColorComponentMap",
    {
      {VK_COLOR_COMPONENT_R_BIT, "R"},
      {VK_COLOR_COMPONENT_G_BIT, "G"},
      {VK_COLOR_COMPONENT_B_BIT, "B"},
      {VK_COLOR_COMPONENT_A_BIT, "A"}
    }
  };

  const Bimap<VkLogicOp> logicOpMap
  {
    "LogicOpMap",
    {
      {VK_LOGIC_OP_CLEAR, "CLEAR"},
      {VK_LOGIC_OP_AND, "AND"},
      {VK_LOGIC_OP_AND_REVERSE, "AND_REVERSE"},
      {VK_LOGIC_OP_COPY, "COPY"},
      {VK_LOGIC_OP_AND_INVERTED, "AND_INVERTED"},
      {VK_LOGIC_OP_NO_OP, "NO_OP"},
      {VK_LOGIC_OP_XOR, "XOR"},
      {VK_LOGIC_OP_OR, "OR"},
      {VK_LOGIC_OP_NOR, "NOR"},
      {VK_LOGIC_OP_EQUIVALENT, "EQUIVALENT"},
      {VK_LOGIC_OP_INVERT, "INVERT"},
      {VK_LOGIC_OP_OR_REVERSE, "OR_REVERSE"},
      {VK_LOGIC_OP_COPY_INVERTED, "COPY_INVERTED"},
      {VK_LOGIC_OP_OR_INVERTED, "OR_INVERTED"},
      {VK_LOGIC_OP_NAND, "NAND"},
      {VK_LOGIC_OP_SET, "SET"}
    }
  };
}